public enum DragonflyStates
{
    Idle,
    EnterToPatrolL,
    PatrolL,
    PreAttackHeadL,
    AttackHeadL,
    BounceHeadL,
    AttackHeadSuccessL,
    FallHeadL,
    CatchSpiderL,
    SpiderPatrolL,
    SpiderPreattackHeadTransitionStateL,
    PreAttackTailL,
    AttackTailL,
    BounceTailL,
    AttackTailSuccessL,
    AttackTailFailL,
    EnterToHoverL,
    HoverL
}
